[package]
name = "r8s_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.5"
owo-colors = "3.5.0"
tokio = { version = "1.26.0", features = ["time", "io-util", "io-std"] }
